# docker-compose -f docker-compose.yaml -p foodie up --build --force-recreate


version: '3.8'

networks:
  Foodie.1:
    external: false
services:
#   apigateway.c:
#     container_name: apigateway.c
#     build:
#       context: ./ApiGateway/
#       dockerfile: 2.dockerfile
#     image: apigateway.c:1    
#     ports:
#       - "8888:8888"
#     networks:
#       - Foodie.1
#     depends_on:
#       - eureka.c

  # userDB.c:
  #   container_name: userDB.c
  #   build:
  #     context: ./User/Db/
  #     dockerfile: db.dockerfile
  #   #image: sqlserver.c:1
  #   # the old way when I wasn't using a dockerfile
  #   #image: mcr.microsoft.com/mssql/server:2019-latest
  #   ports:
  #     - "1435:1433"
  #   networks:
  #     - Foodie.1 

  eureka:
    container_name: eureka
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"
    networks:
      - Foodie.1
  
  # user.1.c:
  #   container_name: user.1.c
  #   build:
  #     context: ./User/
  #     dockerfile: user.dockerfile
  #   image: user.1.c:1
  #   ports:
  #     - "9005:80"
  #   networks:
  #     - Foodie.1
  #   depends_on:
  #     - eureka

  # user.2.c:
  #   container_name: user.2.c
  #   build:
  #     context: ./User/
  #     dockerfile: user.dockerfile
  #   image: user.2.c:1
  #   ports:
  #     - "9006:80"
  #   networks:
  #     - Foodie.1
  #   depends_on:
  #     - eureka
  
  scraper.1.c:
    container_name: scraper.1.c
    build:
      context: ./Scraper/
      dockerfile: Dockerfile
    image: scraper.1.c:1
    ports:
      - "9000:5000"
    networks:
      - Foodie.1
    depends_on:
      - eureka

  
  recipe.1.c:
    container_name: recipe.1.c
    build:
      context: ./Recipe/
      dockerfile: recipe.dockerfile
    image: recipe.1.c:1
    ports:
      - "9001:80"
    networks:
      - Foodie.1
    depends_on:
      - eureka

  recipe.2.c:
    container_name: recipe.2.c
    build:
      context: ./Recipe/
      dockerfile: recipe.dockerfile
    image: recipe.2.c:1
    ports:
      - "9002:80"
    networks:
      - Foodie.1
    depends_on:
      - eureka