from bs4 import BeautifulSoup
from urllib.request import urlopen, Request
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

urls = ['https://claudia.abril.com.br/',
'https://www.acouplecooks.com',
'http://www.afghankitchenrecipes.com/',
'https://akispetretzikis.com/',
'https://ah.nl/',
'https://allrecipes.com/',
# 'https://alltommat.se/',
'https://altonbrown.com/',
'https://amazingribs.com/',
'https://ambitiouskitchen.com/',
'https://archanaskitchen.com/',
'https://www.arla.se/',
'https://www.atelierdeschefs.fr/',
'https://averiecooks.com/',
'https://baking-sense.com/',
'https://bakingmischief.com/',
# 'https://bbc.com/',
# 'https://bbc.co.uk/',
'https://bbcgoodfood.com/',
'https://bettybossi.ch/',
'https://bettycrocker.com/',
'https://bigoven.com/',
'https://blueapron.com/',
'https://bonappetit.com/',
'https://www.bodybuilding.com/',
'https://bowlofdelicious.com/',
'https://budgetbytes.com/',
'https://castironketo.net/',
'https://cdkitchen.com/',
# 'https://chefkoch.de/',
'https://closetcooking.com/',
'https://comidinhasdochef.com/',
'https://cookeatshare.com/',
'https://cookieandkate.com/',
'https://cookingcircle.com/',
'https://cookinglight.com/',
'https://cookpad.com/',
'https://cookstr.com/',
'https://www.coop.se/',
'https://copykat.com/',
'https://countryliving.com/',
'https://cucchiaio.it/',
'https://cuisineaz.com/',
'https://cybercook.com.br/',
'https://www.davidlebovitz.com/',
'https://delish.com/',
'https://www.ditchthecarbs.com/',
'https://domesticate-me.com/',
'https://downshiftology.com/',
'https://www.dr.dk/',
'https://www.eatingbirdfood.com/',
'https://www.eatingwell.com/',
'https://eatsmarter.com/',
'https://eatsmarter.de/',
'https://eatwhattonight.com/',
'https://ethanchlebowski.com/',
'https://epicurious.com/',
'https://recipes.farmhousedelivery.com/',
'https://fifteenspatulas.com/',
'https://finedininglovers.com/',
'https://fitmencook.com/',
'https://food.com/',
'https://food52.com/',
'https://foodandwine.com/',
'https://foodnetwork.com/',
'https://foodrepublic.com/',
'https://www.forksoverknives.com/',
'https://fredriksfika.allas.se/',
'https://www.750g.com',
'https://geniuskitchen.com/',
'https://giallozafferano.it/',
'https://gimmesomeoven.com/',
'https://recietas.globo.com/',
'https://gonnawantseconds.com/',
'https://gousto.co.uk/',
'https://greatbritishchefs.com/',
'https://halfbakedharvest.com/',
'https://www.hassanchef.com/',
'https://headbangerskitchen.com/',
'https://www.heb.com/',
'https://heinzbrasil.com.br/',
'https://hellofresh.com/',
'https://hellofresh.co.uk/',
'https://www.hellofresh.de/',
'https://www.hellofresh.fr/',
'https://www.hellofresh.nl/',
'https://www.homechef.com/',
'https://hostthetoast.com/',
'https://www.ica.se/',
'https://receitas.ig.com.br/',
'https://www.im-worthy.com/',
'https://indianhealthyrecipes.com',
'https://www.innit.com/',
'https://inspiralized.com/',
'https://jamieoliver.com/',
'https://jimcooksfoodgood.com/',
'https://joyfoodsunshine.com/',
'https://justataste.com/',
'https://justbento.com/',
'https://www.justonecookbook.com/',
'https://kennymcgovern.com/',
'https://www.kingarthurbaking.com',
'https://www.kitchenstories.com/',
'https://kochbar.de/',
'http://koket.se/',
'https://www.kptncook.com/',
'https://kuchnia-domowa.pl/',
'https://www.kwestiasmaku.com/',
'https://www.latelierderoxane.com',
'https://lecremedelacrumb.com/',
'https://www.lecker.de',
'https://lekkerensimpel.com',
'https://littlespicejar.com/',
'http://livelytable.com/',
'https://lovingitvegan.com/',
'https://madensverden.dk/',
'https://www.madewithlau.com/',
'https://marleyspoon.com.au/',
'https://marleyspoon.com/',
'https://marleyspoon.de/',
'https://marleyspoon.at/',
'https://marleyspoon.be/',
'https://marleyspoon.nl/',
'https://marleyspoon.se/',
'https://marmiton.org/',
'https://www.marthastewart.com/',
'https://matprat.no/',
'https://meljoulwan.com/',
'https://www.melskitchencafe.com/',
'http://mindmegette.hu/',
'https://minimalistbaker.com/',
'https://misya.info/',
'https://www.mobkitchen.co.uk/',
'https://momswithcrockpots.com/',
'https://monsieur-cuisine.com/',
'http://motherthyme.com/',
'https://mybakingaddiction.com/',
'https://mykitchen101.com/',
'https://mykitchen101en.com/',
'https://www.myplate.gov/',
'https://myrecipes.com/',
'https://healthyeating.nhlbi.nih.gov/',
'https://nourishedbynutrition.com/',
'https://nutritionbynathalie.com/blog',
'https://cooking.nytimes.com/',
'https://ohsheglows.com/',
'https://owen-han.com/',
'https://101cookbooks.com/',
'https://www.paleorunningmomma.com/',
'https://www.panelinha.com.br/',
'https://paninihappy.com/',
'https://https://www.pingodoce.pt/',
'https://popsugar.com/',
'https://practicalselfreliance.com/',
'https://www.primaledgehealth.com/',
'https://przepisy.pl/',
'https://purelypope.com/',
'https://purplecarrot.com/',
'https://rachlmansfield.com/',
'https://rainbowplantlife.com/',
'https://realfood.tesco.com/',
'https://realsimple.com/',
'https://recipetineats.com/',
'https://redhousespice.com/',
'https://reishunger.de/',
'https://rezeptwelt.de/',
'https://sallysbakingaddiction.com',
'https://sallys-blog.de',
'https://www.saveur.com/',
'https://seriouseats.com/',
'https://simplyquinoa.com/',
'https://simplyrecipes.com/',
'https://simplywhisked.com/',
'https://skinnytaste.com/',
'https://southernliving.com/',
'https://spendwithpennies.com/',
'https://www.springlane.de',
'https://steamykitchen.com/',
'https://streetkitchen.hu/',
'https://sunbasket.com/',
'https://sundpaabudget.dk/',
'https://sweetcsdesigns.com/',
'https://sweetpeasandsaffron.com/',
'https://tasteofhome.com',
'https://tastesbetterfromscratch.com',
'https://tastesoflizzyt.com',
'https://tasty.co',
'https://tastykitchen.com/',
'https://theclevercarrot.com/',
'https://thehappyfoodie.co.uk/',
'https://www.thekitchenmagpie.com/',
'https://thekitchn.com/',
'https://thenutritiouskitchen.co/',
'https://thepioneerwoman.com/',
'https://thespruceeats.com/',
'https://thevintagemixer.com/',
'https://thewoksoflife.com/',
'https://timesofindia.com/',
'https://tine.no/',
'https://tudogostoso.com.br/',
'https://twopeasandtheirpod.com/',
'https://www.valdemarsro.dk/',
'https://vanillaandbean.com/',
'https://vegolosi.it/',
'https://vegrecipesofindia.com/',
'https://watchwhatueat.com/',
'https://whatsgabycooking.com/',
'https://www.wholefoodsmarket.com/',
'https://www.wholefoodsmarket.co.uk/',
'https://woop.co.nz/',
'https://woolworths.com.au/shop/recipes',
'https://en.wikibooks.org/',
'https://yemek.com/',
'https://yummly.com/',
'https://zeit.de/(wochenmarkt)',
'https://zenbelly.com/']

# url = 'https://claudia.abril.com.br/'

# page = urlopen(url)

# soup = BeautifulSoup(page, 'html.parser')
# for search in soup.select('input[class*="search"]'):
#     print(url + str(search))
ser = Service('C:\\Users\dgonzalez\\chromedriver_win32\\chromedriver.exe')
driver = webdriver.Chrome(service=ser)
for url in urls:
    driver.get(url)
    time.sleep(1)
    for elem in driver.find_elements(By.CSS_SELECTOR, 'input[class*="search'):
        try:
            print(f"{url} {elem.get_attribute('class')}")
            elem.click()
            elem.clear()
            elem.send_keys('yo')
            elem.send_keys(Keys.ENTER)
            time.sleep(1)
            searchUrl = driver.current_url
            print(searchUrl)
        except:
            continue
        



    # req = Request(url , headers={'User-Agent': 'Mozilla/5.0'})
    # try:
    #     page = urlopen(req).read()
    # except:
    #     print(url)
    #     continue

    # soup = BeautifulSoup(page, 'html.parser')
    # for search in soup.select('input[class*="search"]'):
    #     print(f"{url}  {str(search)}\n")
