server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:

      - id: scraper
        uri: lb://SCRAPER        
        predicates:
        - Path=/scraper/**        
 
      - id: recipeAPI
        uri: lb://RECIPEAPI
        predicates:
        - Path=/recipe/**

      - id: userAPI
        uri: lb://USERAPI
        predicates:
        - Path=/user/**

      - id: userRecipesAPI
        uri: lb://USERRECIPESAPI
        predicates:
        - Path=/userrecipes/**